- id: "nocheckin"
  name: "Pre-commit @nocheckin finder"
  entry: look.sh
  always_run: true
  pass_filenames: false
  language: "script"
  description: "Pre-commit hook which looks for @nocheckin messages in your files"
